name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.name 'your-user-name'
        git config --global user.email 'your-email'

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git remote set-url origin https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}
        npm run deploy
